data1 = input("Please enter a value: ")
data2 = input("Please enter a value: ")
data3 = input("Please enter a value: ")
data4 = input("Please enter a value: ")
data5 = input("Please enter a value: ")
print("data1:{}, data2:{}, data3:{}, data4:{}, data5:{}".format(data1, data2, data3, data4, data5))
